site_name: Biblioteca para microcontroladores sAPI
pages:
- Introducción: index.md
- Metodología de trabajo (desarrolladores): working-methodology.md
- Principios de diseño (desarrolladores): design-rules.md
- Generador de módulos (desarrolladores): module-generator.md
- Tipos de datos: data-types.md
- Periféricos físicos: physical-ip-cores.md
- Periféricos externos y virtuales: virtual-ip-cores.md
- Módulos abstractos: abstract-modules.md
- Utilización de la biblioteca: utilizacion.md
- Ejemplos: ejemplos.md
- API: api_reference_es.md
theme: readthedocs
